name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches:
    - '**'

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.8']
        toxenv: [quality, django32]

    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip
      run: pip install -r requirements/pip.txt

    - name: Set env variable
      run: export AWS_CONFIG_FILE=/dev/null

    - name: Install Dependencies
      run: pip install -r requirements/ci.txt

    - name: Install GNU gettext
      run: sudo apt-get install gettext

    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox
